nvarner/typst-lsp

- src/main.rs
Fix wrong URL to path resolution (I used unwrap since the rest of the code does it like this, might consider handling the error instead but not sure how).
I also removed a useless `drop` because dropping a reference doesn't do anything.
Formatted using rustfmt.
Closes https://github.com/nvarner/typst-lsp/issues/8
> fix: file path resolution on Windows

- src/main.rs
adds hovering support, some repetition with my last pull request that I can factor out once it is merged, I can also rebase after you pulled
> adds hover support from the engine

- Cargo.lock
- Cargo.toml
In order to get reproducible builds, and because typst is very much an actively developed project, I think we shouldn't depend on the main branch.
This PR changes the git dependencies to include a git tag (latest as of now). 
The dependencies have been sorted alphabetically.
> Pin versions for typst and typst-library

- .prettierignore
- addons/vscode/package.json
- addons/vscode/src/extension.ts
- src/command.rs
- src/main.rs
This command is available through the command panel in the IDE and allows to manual trigger the compilation of the active editor (if and only if it's a Typst file).
This will be particularly useful for people that set the automatic compilation setting to `never`.
Closes https://github.com/nvarner/typst-lsp/issues/42
> Add manual PDF creation command

- src/main.rs
Fix the following error when opening a singe file (with no folder in the workspace)
```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/main.rs:26:29
```
fixes #41 
fixes #36
> Fix panic error when unwrapping root_uri without workspace

- .github/workflows/release.yml
Trying to fix the new error in the alpine release job. It seems the environment variable `target` was not set properly.
Switching to the `env` key in the yaml instead of printing to `$env:GITHUB_ENV` which I suspect doesn't persist across steps.
> ci: more fixes for release workflow

- .gitignore
- addons/vscode/package.json
- addons/vscode/src/extension.ts
This PR adds a new conguration item `serverPath` to override the default bundled server. Closing #55.
> feat: add configuration `serverPath`

- flake.lock
- flake.nix
This allows Nix users to install typst-lsp just by specifying the GitHub repository. Since typst-lsp isn't packaged anywhere yet that is quite useful. It also provides a development shell that includes some basic rust tools and Node.js. It's mostly based on the [flake in the typst repo](https://github.com/typst/typst/blob/main/flake.nix). I tested both the package as well as the devshell and found no issues.
> Add Nix Flake

- src/server/lsp.rs
Currently, auto-exporting the PDF on save doesn't work with the [Helix editor](https://github.com/helix-editor/helix). This is because in the `text_document_sync` server capability, typst-lsp doesn't include the capability for save notifications. As far as I understand, the client shouldn't send save notifications in this case(see the [documentation of TextDocumentSyncOptions in the LSP specification](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_didRename)). Adding the capability fixes the issue for me. I'm guessing that this isn't an issue VSCode because VSCode isn't fully spec compliant and just sends the notification anyway.
The LSP specification isn't super clear on this so if I misunderstood it, please let me know. In that …
> Add the LSP capability for save notifications

- src/server/lsp.rs
- src/server/symbols.rs
The AST structure changed in the latest version of typst apparently, so it broke document symbols for functions and variables.
This PR fixes it so variables and functions appear in the document and workspace symbols listing.
> Fix document symbols for functions and variables

- src/server/lsp.rs
- src/server/mod.rs
- src/server/selection_range.rs
This allows [this VSCode feature](https://code.visualstudio.com/docs/editor/codebasics#_shrinkexpand-selection) to work. I think it might be particularly useful for editing math in Typst.
> Implement selectionRange request

- README.md
Installation Guide Added.
Installation steps for Neovim are sometimes intractable for new users. It is necessary to give a concise guide to the key points in it.
> Add Installation Guide in README.md

- flake.lock
- flake.nix
Switch to fenix in order to meet the requirements of Rust 1.70+ for typst.
Built on x86_64-linux.
See: https://github.com/typst/typst/pull/1450
> fix nix flake

- addons/vscode/package.json
- src/config.rs
- src/lsp_typst_boundary/world.rs
- src/server/mod.rs
This PR introduces a new configuration option called `rootPath`. In the original typst application, this configuration could be set using the `--root` command-line parameter or the `TYPST_ROOT` environment variable.
Closing #98 and #120.
> make `rootPath` configurable

- addons/vscode/package.json
- src/config.rs
- src/ext.rs
- src/server/semantic_tokens/mod.rs
- src/server/semantic_tokens/token_encode.rs
- Use correct highlighting for variables
- Don't highlight entire expressions as operators
- Remove unneeded code
> Syntax Highlighting Fixes

- flake.nix
- src/workspace/source_manager.rs
Previously, an ID was always generated for each new URL by the source manager, but there wouldn't always be a corresponding insertion into the actual sources cache.
This commit fixes the issue by removing the added ID entry when an error occurs and a source item could not be added to the cache.
Should fix #183
> Ensure id set and sources vec stay in sync

- src/workspace/package/manager.rs
We can edit typst files (even with `#import`) without a workspace in v0.7, but cannot in v0.8 – v0.9.3. This PR gets the feature back.
If `PackageManager` tries to resolve a package and finds nothing (e.g. `current` is empty because there's no workspace), we create a temporary package from the file's parent directory.
- Resolves: #232
- Investigation: https://github.com/nvarner/typst-lsp/issues/232#issuecomment-1684206544
(I've only tested it in VS Code)
This PR is implemented as a few `or_else(…)`, so I guess it won't break any existing functions.
Can `CurrentPackageError::NotFound` ever reach? Should we remove it?
> fix(regression): Basic single file support

- src/server/formatting.rs
- src/server/lsp.rs
If we have a `typstfmt-config.toml` in the working directory, use that. Otherwise, look for it in the project root. Otherwise, use the default config. This seemed the most sensible thing to me.
> Read typstfmt config from files, if possible

- src/lsp_typst_boundary.rs
Adds related information to the diagnostics based on the trace points provided by typst itself.
This is my first time interacting with this codebase so if you spot anything that could be improved, please do let me know!
Before the change:
After the change:
> Add related information to typst diagnostics

- .github/workflows/full_build.yml
Based on microsoft/vscode-vsce#908 and microsoft/vscode#195559, it appears that extensions should no longer be published for the now removed `win32-ia32` target.
> Don't build for VS Code target `win32-ia32`

- src/server/document.rs
- src/server/export.rs
- src/server/lsp.rs
- src/server/mod.rs
- src/server/typst_compiler.rs
fix #157
There are mainly 3 changes:
1. Compile source to document even if no export is required.
2. Use `Arc<Document>` to avoid heavy clones
3. Add a document field to TypstServer and update it when compiling success.
> Add auto complete for citations

- src/server/lsp.rs
fix #380. The issue is caused by we set `explicit` of `typst_ide::autocomplete` to true but it is actually not. Note that this PR doesn't provide a way to determining whether a completion request is explicit, but I still think of the change introduced by PR is an improvement.
From comment of `typst_ide::autocomplete`:
> When `explicit` is `true`, the user requested the completion by pressing control and space or something similar.
However, from <https://github.com/microsoft/language-server-protocol/issues/1101>
> As of LSP 3.16, CompletionTriggerKind takes the value Invoked for both manually invoked (for ex: ctrl + space in VSCode) completions and always on (what the spec refers to as 24/7 completions).
Hence, we cannot distinguish between the two cases (ctrl + space case or 24/7 case) in …
> Always use implicit autocomplete

- src/workspace/package/external/manager.rs
- src/workspace/package/external/mod.rs
- src/workspace/package/external/remote_repo.rs
- src/workspace/package/manager.rs
- src/workspace/project.rs
- src/workspace/world/mod.rs
Close #367 and close #383. It mainly adds `ExternalPackageManager::packages` that read the index file once from network. Then, the result will be used by typst for autocompletion.
---
Result
> Autocompletion for package import

- editors/vscode/package.json
- editors/vscode/src/extension.ts
- src/config.rs
- src/server/command.rs
- src/server/document.rs
- src/server/hover.rs
- src/server/lsp.rs
- src/server/mod.rs
This PR proposes an abstraction corresponding to "Preview this file" in official webapp. In conclusion, this PR adds a "typst-lsp.doPinMain" command to lsp program which could then get used by:
+ user manually runs command "typst-lsp.pinMainToCurrent" or "typst-lsp.unpinMain" in VSCode.
+ user writes some lua script to automate the pin action.
+ some other vscode extension (such as typst-preview) pins a previewing file automatically.
---
Usage 1: improve mode of exportPDF by adding "onPinnedMain{Save,Type}".
Currently, automatically exportPDF on save or on type is annoying since typst-lsp cannot identify the source files that has empty content. This PR can allow users only exporting PDF "onPinnedMain{Save,Type}", close #11, may close #184, may close #285.
---
Usage 2: make hover tip and …
> Add capability to pin a main file

- editors/vscode/package.json
This fixes a typo in the VSCode command actions (`openning` -> `opened`) and slightly rewords another action (`open` -> `opened`) to be more consistent with the others.
> Fixed typo + improved language consistency in VS Code command titles

- src/server/formatting.rs
The typstfmt binary uses `typstfmt.toml` or `.typstfmt.toml` instead of `typstfmt-config.toml` (see the source code [here](https://github.com/astrale-sharp/typstfmt/blob/2093a920f64d947cb8d6ecc7846a2e4bf11b5216/src/main.rs#L18C7-L18C23)). This pull request makes it so we use the same names.
One question: would we want to also continue supporting `typstfmt-config.toml` for backwards compatibility? Or is it fine that we don't since formatting is experimental?
> match upstream typstfmt config file name
